
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

login=/WEB-INF/views/login.jsp
signUp=/WEB-INF/views/SignUp.jsp
register=ecomm.model.Register
lfail=/WEB-INF/views/LoginFail.jsp
verify=/WEB-INF/views/Loginverify.jsp
admin=/WEB-INF/views/adminview.jsp
buyer=/WEB-INF/views/LoginSuccesful.jsp
lmodel=ecomm.model.LoginModel
