
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template
index=/index.jsp
login=/WEB-INF/views/Login.jsp
signUp=/WEB-INF/views/SignUp.jsp
register=ecomm.model.Register
lfail=/WEB-INF/views/LoginFail.jsp
verify=/WEB-INF/views/LoginVerify.jsp
admin=/WEB-INF/views/AdminView.jsp
idisplay=ecomm.model.DisplayItem
lmodel=ecomm.model.LoginModel
emailverifier=ecomm.model.EmailVerifier
emvf=/WEB-INF/views/EmailVerify.jsp
chmail=/WEB-INF/views/CheckMail.jsp
nameavail=ecomm.model.Availablity
frmpro=ecomm.model.FormModel
sellerlg=/WEB-INF/views/SellerLogin.jsp
sellerlgmodel=ecomm.model.Seller_Login
uploaditem=ecomm.model.UploadItem
chandler=ecomm.model.Categoryhandler
schandler=ecomm.model.SubCategoryHandler
itd=/WEB-INF/views/ItemDisplay.jsp
productDetails=/WEB-INF/views/ProductDetails.jsp
spd=ecomm.model.SingleProductDetails
addToCart=ecomm.model.AddToCart